
export const INTERSECTION_ENTRY_MARGIN = 0.05; 
export const ROAD_END_RATIO = 1 - INTERSECTION_ENTRY_MARGIN;
export const ROAD_BEGIN_RATIO = INTERSECTION_ENTRY_MARGIN;
export const MAX_ROAD_LENGTH = 200;
export const INTERSECTION_SNAP_RADIUS = 10;
export const MIN_ANGLE_DEGREES = 20;
